import {useEffect,useRef,useState} from 'react';
import MoaLogo from './MoaLogo';
export default function LaunchGate({children}){
 const kakao=/KAKAOTALK/i.test(navigator.userAgent),ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
 const [standalone,setStandalone]=useState(()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true);
 const [prompt,setPrompt]=useState(null),[help,setHelp]=useState(false),[fallback,setFallback]=useState(false),[message,setMessage]=useState('');const timer=useRef(null);
 const url=new URL(location.href);url.hash='';
 useEffect(()=>{const media=matchMedia('(display-mode: standalone)');const change=()=>setStandalone(media.matches||navigator.standalone===true);const available=e=>{e.preventDefault();setPrompt(e);};const installed=()=>{change();setPrompt(null);setMessage('추가한 홈 화면 아이콘으로 열어 주세요.');};media.addEventListener('change',change);window.addEventListener('beforeinstallprompt',available);window.addEventListener('appinstalled',installed);return()=>{media.removeEventListener('change',change);window.removeEventListener('beforeinstallprompt',available);window.removeEventListener('appinstalled',installed);clearTimeout(timer.current);};},[]);
 const install=async()=>{if(!prompt){setHelp(true);return;}try{await prompt.prompt();const result=await prompt.userChoice;setMessage(result.outcome==='accepted'?'설치를 요청했어요. 홈 화면 아이콘으로 열어 주세요.':'나중에 다시 추가할 수 있어요.');}catch{setHelp(true);}finally{setPrompt(null);}};
 if(kakao)return <main className="external-browser-entry"><a className="external-browser-link" href={'kakaotalk://web/openExternal?url='+encodeURIComponent(url.href)} onClick={()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>setFallback(true),2200);}}>새창으로 접속하기 ↗</a>{fallback&&<div className="external-browser-help"><p>열리지 않으면 카카오톡 메뉴에서 외부 브라우저로 열어 주세요.</p><button onClick={async()=>{try{await navigator.clipboard.writeText(url.href);setMessage('주소를 복사했어요. Safari 또는 Chrome에 붙여 넣어 주세요.');}catch{setMessage(url.href);}}}>주소 복사</button><p role="status">{message}</p></div>}</main>;
 if(standalone)return children;
 return <main className="profile-screen personal-entry install-entry"><header><b><MoaLogo/></b></header><img src="/icon-192.png" alt="단어모아 앱 아이콘" width="88" height="88"/><h1>홈 화면에서<br/>바로 시작해요</h1><p>홈 화면에 추가한 단어모아 아이콘으로 실행하면 시작할 수 있어요.</p><button className="account-primary" onClick={install}>홈 화면에 추가하고 바로 시작하기</button>{help&&<section className="install-instructions" aria-label="홈 화면 추가 방법"><h2>{ios?'아이폰에서 추가하기':'브라우저에서 추가하기'}</h2><ol><li>{ios?'Safari의 공유 메뉴를 열어 주세요.':'브라우저 메뉴를 열어 주세요.'}</li><li>{ios?'‘홈 화면에 추가’를 선택해 주세요.':'‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택해 주세요.'}</li><li>추가한 단어모아 아이콘으로 열어 주세요.</li></ol></section>}<p role="status">{message}</p></main>;
}
